### ISSUE TITLE
Enhancing Teachers Dashboard

### ISSUE THREAD

**Issue by coding-geek21** [coding-geek21/classDeck#12]

**Comment by chinmayparekh** [comment]
I would like to work on it @coding-geek21 @yaswanthsaivendra

**Comment by laraib-786** [comment]
I would like to work on it @coding-geek21

**Comment by Ashsenior** [comment]
Hey , @coding-geek21 are u planning on splitting your backend and frontend with react ? It will make the webapp more robust and open to many other features . If u want I can work on it and can also work on the quiz section and add new categories of questions like one word , match , long etc to the quiz section .

**Comment by Abhishek2408** [comment]
Hey, @coding-geek21 actually I'm facing one issue while installing the requirements it is showing me metadata-generation-failed. can u please help me to solve this

**Comment by chinmayparekh** [comment]
Can I add basic animations in the cards in teacher homepage as part on enhancement. I will make it responsive.

**Comment by coding-geek21** [comment]
> Can I add basic animations in the cards in teacher homepage as part on enhancement. I will make it responsive.

Yes go ahead

**Comment by chinmayparekh** [comment]
okay, i will do it by tonight.
