### ISSUE TITLE
Enhancing Students Dashboard

### ISSUE THREAD

**Issue by coding-geek21** [coding-geek21/classDeck#13]

**Comment by chinmayparekh** [comment]
I would like to work on it @coding-geek21 @yaswanthsaivendra

**Comment by chinmayparekh** [comment]
Het @coding-geek21 @yaswanthsaivendra I am facing issue in running the server. I am getting WSGI application could not be loaded (I guess it was changed while hosting the site) ,i am unable to resolve it. I have attached the errors which i encountered with this message
![Screenshot from 2022-03-02 16-16-56](https://user-images.githubusercontent.com/76399431/156347295-8c345d40-41b3-483d-ab12-c272c88cf453.png)

**Comment by sumanth2002629** [comment]
I was also facing the same issue.

**Comment by yaswanthsaivendra** [comment]
@chinmayparekh , You badly changed the versions in requirements without ensuring the compatibility . Now it's updated, hopefully this shouldn't be a problem now.
