### ISSUE TITLE
README description

### ISSUE THREAD

**Issue by kaustav202** [coding-geek21/classDeck#2]
The project needs a brief readme section devoted to what is it's functionality and what it does. This will help new comers in getting accustomed and provide a broad overview.

**Comment by shubhsardana29** [comment]
Hi, I'm GSSOC'22 participant, would love to work on this issue. Could you please assign me this? 
Thank you.

**Comment by kaustav202** [comment]
I can take up this issue if it's assigned to me.

**Comment by kaustav202** [comment]
> I can take up this issue if it's assigned to me.

for gssoc22

**Comment by satyam4484** [comment]
could you explain your project what its all about

**Comment by coding-geek21** [comment]
> The project needs a brief readme section devoted to what is it's functionality and what it does. This will help new comers in getting accustomed and provide a broad overview.

Go ahead with this issue

**Comment by coding-geek21** [comment]
> Hi, I'm GSSOC'22 participant, would love to work on this issue. Could you please assign me this? Thank you.

Issues will be assigned based on first come first serve.. So look for some other issue

**Comment by coding-geek21** [comment]
> could you explain your project what its all about

You can check up the project description and project details on gssoc website... 
This project is all about online classroom in django,  Check this video you will get an idea 
https://www.youtube.com/watch?v=SVEMykwTRBE&feature=youtu.be

**Comment by chinmayparekh** [comment]
Hi, I am a GSSOC'22 participant and I would love to make the Readme documentation better by including steps for setting up the virtual environment,install requirements and then running the code. Could you please assign this issue to me?

**Comment by coding-geek21** [comment]
> Hi, I am a GSSOC'22 participant and I would love to make the Readme documentation better by including steps for setting up the virtual environment,install requirements and then running the code. Could you please assign this issue to me?

All these are already added

**Comment by adi7yashah** [comment]
I am a participant of GSSOC'22. I want to work on this issue .Can you please aassign me?

**Comment by coding-geek21** [comment]
@kaustav202  It has been two days already but there is no update so I'm assigning someone else

**Comment by coding-geek21** [comment]
@shubhsardana29  Go ahead with this issue. Make sure that you complete by 1 day

**Comment by kaustav202** [comment]
Okay I was just about to push the changes. but it's ready btw in case you need it. : ) @coding-geek21

**Comment by coding-geek21** [comment]
> Okay I was just about to push the changes. but it's ready btw in case you need it. : ) @coding-geek21

Okay then make PR

**Comment by kaustav202** [comment]
Yes sure but would you like to tell me about some additional info or what is your vision regarding this so that I can fill in.
It is a all in one comprehensive virtual classroom project which is inspired from likes of google classroom right ?
@coding-geek21

**Comment by coding-geek21** [comment]
> Yes sure but would you like to tell me about some additional info or what is your vision regarding this so that I can fill in. It is a all in one comprehensive virtual classroom project which is inspired from likes of google classroom right ? @coding-geek21

Yeah it's similar to google classroom but it has some extra features like options to create test in this platform as well as viewing results
Ultimate goals of this project would be something like Teams platform where we have seperate channels for each subjects. 
View students , teachers 
Creating profile for teachers and students
Students can attend tests, view results, submit assignments etc
Teachers can give tests, view edit students list, create assignments etc
Create a calendar to view the schedule of test and assignments (for both teacher and students)
Try to make all these as a point

Include tech stack as heading and add the techstacks as labels

**Comment by kaustav202** [comment]
Okay got it.

**Comment by kaustav202** [comment]
review the changes @coding-geek21

**Comment by kaustav202** [comment]
@coding-geek21 could you change the assignee for this issue..  will it effect gssoc22 count?
