### ISSUE TITLE
Enhancing sign up dashboard 

### ISSUE THREAD

**Issue by iamtanya-22** [coding-geek21/classDeck#22]

**Comment by iamtanya-22** [comment]
I want to work on it by making the UI look good on laptops as well as on PC.
So, assign this issue to me.

**Comment by coding-geek21** [comment]
Go ahead with this issue. Complete it within 2 days

**Comment by HarshKumarChoudary** [comment]
I would like to work on this issue. I'm a GSSOC 22 participant. Please assign it to me, if the issue is not resolved. Thanks.

**Comment by coding-geek21** [comment]
any updates? @iamtanya-22

**Comment by iamtanya-22** [comment]
@coding-geek21  Yes, I'm working on it and I'll complete it by today.

**Comment by iamtanya-22** [comment]
@coding-geek21  I'm finding some error in the code and still working on it so you can assign this issue to @HarshKumarChoudary .

**Comment by MitAbhay** [comment]
@coding-geek21  I think this issue is still pending, can I go through this ??

**Comment by HarshKumarChoudary** [comment]
yes, Sorry I was busy with some College works. You can go ahead with it. @coding-geek21  please unassign me. Thanks.

**Comment by coding-geek21** [comment]
> @coding-geek21 I think this issue is still pending, can I go through this ??

Since you were assigned #56 and this is almost the same issue.. I'm closing this
