### ISSUE TITLE
Enhancement of Navbar 

### ISSUE THREAD

**Issue by abhinav2712** [coding-geek21/classDeck#25]
The navbar can be improved, it look odd here.I can improve the UI of that, please assign this issue under gssoc'22 and I would like to work on it

**Comment by coding-geek21** [comment]
any updates @abhinav2712

**Comment by HarshKumarChoudary** [comment]
I would like to work on this issue. I'm a GSSOC 22 participant. Please assign it to me, if this issue is not resolved till now. Thanks.

**Comment by coding-geek21** [comment]
@HarshKumarChoudary  Complete it within 2 days

**Comment by Anish1411** [comment]
I would like to work on this issue under GSSOC'22  , incase others are unable to resolve it

**Comment by HarshKumarChoudary** [comment]
@coding-geek21 , I have enhanced the navbar code with CSS buttons  and gradient effects. Also I made navbar to move and stay sticky to header as user scrolls. Hope you will like it.

**Comment by HarshKumarChoudary** [comment]
I created the PR #41 .
Please review it and merge it. Thanks.

**Comment by HarshKumarChoudary** [comment]
I made some changes as requested to the PR. Please review it.

**Comment by HarshKumarChoudary** [comment]
I closed previously created PR #41 and recreated another PR #57 . Please review it. Thanks.
