### ISSUE TITLE
Issue in settings.py

### ISSUE THREAD

**Issue by sumanth2002629** [coding-geek21/classDeck#26]
"python3 manage.py runserver" should run without any warnings.

It was showing warnings as shown in the attached file. They can be removed by adding the below line to settings.py

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'.
![issue](https://user-images.githubusercontent.com/76842817/156493517-d44d96ae-4d57-4674-aff6-cd2e201763df.png)

**Comment by yaswanthsaivendra** [comment]
@sumanth2002629 , Make sure you are using the correct `django` version. Currently we are using a version which is `3.0.x` . This should be a problem when we are using a version >=django 3.2 . So, a direct bump to version 3.2 or 4 considering all compatibility and changing the codebase accordingly could be considered as an `issue`.

**Comment by sumanth2002629** [comment]
I will check this out later. If not possible I will close the issue.
