### ISSUE TITLE
No option to add a subject(channels feature)

### ISSUE THREAD

**Issue by sumanth2002629** [coding-geek21/classDeck#30]
Teacher does not have an option to add a subject. As soon as teacher logs in, he/she should see the 4th option of adding a subject too.
Please assign this issue to me. I like to work on this.

**Comment by coding-geek21** [comment]
> Teacher does not have an option to add a subject. As soon as teacher logs in, he/she should see the 4th option of adding a subject too. Please assign this issue to me. I like to work on this.

So you want to add an extra field ( subject ) for teachers right? In sign up page?

**Comment by sumanth2002629** [comment]
I want to add a subject, but not on the signup page. Because teacher may want to offer a new subject after signing up also. So adding a new subject should be visible along with the three other cards(create tests, create assignments, calendar) after the teacher logs in.

**Comment by coding-geek21** [comment]
@yaswanthsaivendra  What do you think?

**Comment by sumanth2002629** [comment]
Also, students should be able to select the subjects after logging in (If some teacher adds a new subject). These two I can implement.

**Comment by yaswanthsaivendra** [comment]
@sumanth2002629 , We are currently redefining user authentication so as to achieve these as our next proceedings in our project. We need a way for teachers to create subjects and add only certain students to access those subjects. To be precise , we call this feature as `channels`(a channel is for a subject) which can be created by teachers and add certain students in them via sending links via mail etc. Later these kind of access restrictions will be implemented over tests and assignments.
So if u are sure about working alongside with other work in progress(auth stuff) to create channels and can later change them to fit with auth stuff , u may proceed with this `issue`.

**Comment by yaswanthsaivendra** [comment]
otherwise u may wait for a while until auth stuff get done and can proceed with this!!

**Comment by sumanth2002629** [comment]
Yeah, then I will proceed once auth stuff is done.

**Comment by coding-geek21** [comment]
> Yeah, then I will proceed once auth stuff is done.

Ok then i will assign you

**Comment by coding-geek21** [comment]
Any updates? @sumanth2002629

**Comment by sumanth2002629** [comment]
As suggested by @yaswanthsaivendra ,can I work on this after auth stuff is completed or else I will try to work on this from next weekend, I am a bit busy this week.

**Comment by coding-geek21** [comment]
> As suggested by @yaswanthsaivendra ,can I work on this after auth stuff is completed or else I will try to work on this from next weekend, I am a bit busy this week.

okay fine

**Comment by yaswanthsaivendra** [comment]
> As suggested by @yaswanthsaivendra ,can I work on this after auth stuff is completed or else I will try to work on this from next weekend, I am a bit busy this week.

We are done with all main changes in auth stuff, U can proceed with this issue, when u find time .

**Comment by coding-geek21** [comment]
@sumanth2002629 Any updates?

**Comment by sumanth2002629** [comment]
Yes,i have started working on it.It will be done in 3-4 days. Sorry for the delay.

**Comment by sumanth2002629** [comment]
Sorry for the inconvenience, but something unexpected came up today. I guess I can't work on this issue so kindly assign this issue to others.

**Comment by m-a-rahul** [comment]
Hey @coding-geek21! I would like to take up this issue... Could you assign it to me?

**Comment by coding-geek21** [comment]
@m-a-rahul  would you like to work on it?

**Comment by m-a-rahul** [comment]
Yea, I would like to work on it! Kindly reassign the task I will deliver it asap
