### ISSUE TITLE
Enhancement of teachers quiz homepage

### ISSUE THREAD

**Issue by Kritinp** [coding-geek21/classDeck#31]
This html file needs  to be restructured to make it more user-friendly
![Screenshot from 2022-03-03 19-33-36](https://user-images.githubusercontent.com/79003711/156580052-7aeeb673-1dd9-40a9-bd29-e37407455e02.png)

**Comment by Kritinp** [comment]
Pull request sent

**Comment by coding-geek21** [comment]
@Kritinp Any updates?
