### ISSUE TITLE
[FEAT] Adding docker files for deployment 

### ISSUE THREAD

**Issue by truthfool** [coding-geek21/classDeck#36]
- Adding docker files for ease of deployment

**Comment by coding-geek21** [comment]
As of now, I don't think it's so important. So I'm closing this issue

**Comment by truthfool** [comment]
Any issues I can contribute to?

**Comment by coding-geek21** [comment]
check #60 or you yourself can create any issues @truthfool

**Comment by truthfool** [comment]
okay
Thanks for your response.
I'll describe the solution and make a PR.
