### ISSUE TITLE
Making all pages related to teachers quiz/question dashboard uniform with changes made in issue #31

### ISSUE THREAD

**Issue by Kritinp** [coding-geek21/classDeck#38]
![QuizDetails](https://user-images.githubusercontent.com/79003711/156870881-858d2577-6687-4c2d-8a2c-c6a73abef9f1.png)
Old Quiz Details Page

![QuizResults](https://user-images.githubusercontent.com/79003711/156870910-476366e8-02d5-4cdf-a110-5e9a555bc498.png)
Old Quiz Results Page

![QuizDelete](https://user-images.githubusercontent.com/79003711/156870917-c93eabb9-cc8f-4c1d-89c3-dd67591ba036.png)
Old Quiz Delete Page

![QuestionAdd](https://user-images.githubusercontent.com/79003711/156870923-fb3294fc-fca8-44e9-b36e-62ebe0bc0c44.png)
Old Question Add Page

![QuestionDetails](https://user-images.githubusercontent.com/79003711/156870932-ddde5213-2938-4f78-a65e-afe82c15012c.png)
Old Question Details Page

![QuestionDelete](https://user-images.githubusercontent.com/79003711/156870943-184375b3-574f-4228-95f8-784c4b8f99ee.png)
Old Question Delete Page

--------------------
These pages must be made to match the changes made to quiz_add_form and quiz_change_list which were made earlier according to issue #31 as shown below
![issue31](https://user-images.githubusercontent.com/79003711/156871077-c374de17-8341-4362-b17e-742030bbbf1b.png)

-------------------
Please assign this so that I can complete this work.
Note: Pull request for issue #31 pending

**Comment by coding-geek21** [comment]
Go ahead @Kritinp

**Comment by coding-geek21** [comment]
Since you are enhancing many pages in one issue i will give you level 3 label

**Comment by coding-geek21** [comment]
@Kritinp  any updates?

**Comment by Kritinp** [comment]
> @Kritinp any updates?

Almost done!

**Comment by coding-geek21** [comment]
@Kritinp  Any updates? when will you make PR?

**Comment by Kritinp** [comment]
> @Kritinp Any updates? when will you make PR?

Will finish it tonight

**Comment by Kritinp** [comment]
> @Kritinp Any updates? when will you make PR?

I have fixed this issue by updating the existing PR.
