### ISSUE TITLE
Enhancemnet of footer 

### ISSUE THREAD

**Issue by Abhishek2408** [coding-geek21/classDeck#44]
Footer is looking very simple. i want to make some changes in it like logo and some info of class deck and class deck social media handlers etc.

**Comment by bhavyapathak20** [comment]
@coding-geek21  I would like to contribute on this issue with @Abhishek2408. If it is okay?

**Comment by coding-geek21** [comment]
> @coding-geek21 I would like to contribute on this issue with @Abhishek2408. If it is okay?

Only one can work on the issue at a time. please look for some other issue

**Comment by Abhishek2408** [comment]
@bhavyapathak20 I'm already working on it

**Comment by Abhishek2408** [comment]
@coding-geek21 i have one doubt i haven't create branch before start editing so any suggestion what i have to do now??

**Comment by Abhishek2408** [comment]
@coding-geek21 if any suggestion please let me know
Before
![image](https://user-images.githubusercontent.com/87486132/156931572-c1040fdd-451f-4a9c-96ab-02f5f2bed23c.png)
After
![image](https://user-images.githubusercontent.com/87486132/156931541-37e4073f-9b30-4f17-bd6c-daa2f8463ba9.png)

**Comment by Harshil-Jani** [comment]
> @coding-geek21 i have one doubt i haven't create branch before start editing so any suggestion what i have to do now??

No issues. Unless and untill you do `git add .` your changes won't affect `[develop]` branch of your fork. So, before you write `git commit -m "anything" ` just do `git checkout -b <branch-name>`.
