### ISSUE TITLE
update Readme file

### ISSUE THREAD

**Issue by coding-geek21** [coding-geek21/classDeck#45]

**Comment by chinmayparekh** [comment]
Can you assign this issue to me?

**Comment by chinmayparekh** [comment]
I understand that this issue was already resolved but I have elaborated on how to setup the .env file much better, could you just check it once?

**Comment by coding-geek21** [comment]
> I understand that this issue was already resolved but I have elaborated on how to setup the .env file much better, could you just check it once?

Yeah but that is not needed for contributors they just need to copy paste the template that's enough and all the libraries are already imported in settings.py so there is no work for contributors

**Comment by chinmayparekh** [comment]
okay got it.
