### ISSUE TITLE
Add forgot password feature

### ISSUE THREAD

**Issue by coding-geek21** [coding-geek21/classDeck#46]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Define You

- [ ] GSSoC22 Participant
- [ ] Contributor

## Is your feature request related to a problem? Please describe.

Create forgot password feature

## Approach to be followed (optional):

- add forgot password link in login page
- on clicking the link it should ask the email of the user
- check if the user is available in users list (backend)
- if found send the link for password reset through mail and display message "Password reset link sent to your mail"
- on clicking the link in mail user should get redirected to form asking new password and confirm password
-  Display message "Successfully updated password"

## Screenshots Or Video

Attach screenshots or video if applicable

**Comment by chinmayparekh** [comment]
Can I work on this from next week, I am busy this week?

**Comment by coding-geek21** [comment]
> Can I work on this from next week, I am busy this week?

Yeah

**Comment by chinmayparekh** [comment]
Okay thanks

**Comment by m-a-rahul** [comment]
I am Rahul, GSSOC2022 Contributor. I have good knowledge about the basic structures of Django. I would like to take upon the _"Forgot Password"_ feature. I have shared my approach below, if you're satisfied assign it to me, I will deliver the attribute to your best suit.

### Approach

1. The solution includes the usage of the default **auth_views** package which comes with four URL endpoints that facilitate the _"Forgot Password"_ feature.
2. The package captures the registered user email as the first step and shows a success message once the account has been identified and a mail containing the reset instructions are sent.
3. The reset option follows a **token-based authorization** which identifies the user access.
4. The final form includes two password fields _"New Password"_ and _"Confirm New Password"_. On form submission, the password is successfully reset and a success message is displayed.

### Additional Context

The Figma file shared below shows the skeleton of the given approach which will be modified to fit **ClassDeck**
https://bit.ly/3HQZU6G

Write back if you find the approach satisfying enough and I will start working on it right away!

**Comment by coding-geek21** [comment]
> I am Rahul, GSSOC2022 Contributor. I have good knowledge about the basic structures of Django. I would like to take upon the _"Forgot Password"_ feature. I have shared my approach below, if you're satisfied assign it to me, I will deliver the attribute to your best suit.
> 
> ### Approach
> 1. The solution includes the usage of the default **auth_views** package which comes with four URL endpoints that facilitate the _"Forgot Password"_ feature.
> 2. The package captures the registered user email as the first step and shows a success message once the account has been identified and a mail containing the reset instructions are sent.
> 3. The reset option follows a **token-based authorization** which identifies the user access.
> 4. The final form includes two password fields _"New Password"_ and _"Confirm New Password"_. On form submission, the password is successfully reset and a success message is displayed.
> 
> ### Additional Context
> The Figma file shared below shows the skeleton of the given approach which will be modified to fit **ClassDeck** https://bit.ly/3HQZU6G
> 
> Write back if you find the approach satisfying enough and I will start working on it right away!

Great go ahead with this issue!
