### ISSUE TITLE
Create timer for quiz

### ISSUE THREAD

**Issue by coding-geek21** [coding-geek21/classDeck#49]
## Is your feature request related to a problem? Please describe.

Create timer feature for quiz 

## Approach to be followed (optional):

-  The quiz page should automatically exit if the time exceeds
-  Time left should be displayed and should be dynamically updating so that user can see it 

## Screenshots Or Video

Attach screenshots or video if applicable

**Comment by HarshKumarChoudary** [comment]
HI, I would like to work on it. Please assign it to me.

**Comment by coding-geek21** [comment]
@HarshKumarChoudary any update?

**Comment by HarshKumarChoudary** [comment]
Ya I'm working on it. Hope to create a PR by tomorrow.

**Comment by coding-geek21** [comment]
@HarshKumarChoudary When will you make PR? are you working on this?

**Comment by HarshKumarChoudary** [comment]
@coding-geek21  sorry, I got busy with exams and holidays. I will make PR soon.

**Comment by sahilg861907** [comment]
hello @coding-geek21 , if it's not done yet, can you please assign it to me? I'm very excited to take up this task! also I think Harsh is busy with his exams and Holidays , so please assign it to me since I m ready to contribute on this issue under GSSOC'22.

**Comment by dvlsatya** [comment]
can you assign this to me?

**Comment by coding-geek21** [comment]
@dvlsatya any updates??

**Comment by Ashsenior** [comment]
Hey , @coding-geek21 please assign this issue to me .
