### ISSUE TITLE
Enhance the footer

### ISSUE THREAD

**Issue by krithika2411** [coding-geek21/classDeck#59]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ✔️] I am running the latest version
- [✔️ ] I checked the documentation and found no answer
- [ ✔️] I checked to make sure that this issue has not already been filed

## Define You

- [ ✔️] GSSoC22 Participant
- [✔️ ] Contributor

## Describe the bug
I was going through the website and  I found that in home page there is no footer information like contact us and social media links.

## Expected Behavior
there should be a footer available so user can connect more and get to know better
Please describe the behavior you are expecting.

## Screenshots Or Video
![Screenshot (284)](https://user-images.githubusercontent.com/85842586/157269738-340f767d-41e0-4dca-b0ab-b410426e3145.png)

**Comment by krithika2411** [comment]
kindly please assign this issue under Gssoc'22.

**Comment by coding-geek21** [comment]
Footer is already there right @krithika2411. Do you want to enhance it?

**Comment by krithika2411** [comment]
Yes , i would like to add more info in it.

**Comment by coding-geek21** [comment]
can you tell briefly? and also please update your forked repo by doing `git pull`

**Comment by krithika2411** [comment]
i would like to add the contact details like social media handles and address or phone number , class deck logo a little bit about it  and redirect navbar items like faqs

**Comment by krithika2411** [comment]
@coding-geek21 can i start working on this , kindly assign me this under GSSOC'22

**Comment by coding-geek21** [comment]
![image](https://user-images.githubusercontent.com/53329034/157360569-16b07f17-1e7c-4993-b749-afa362211d7d.png)
 this is how it looks now you can still enhance  it

**Comment by coding-geek21** [comment]
@krithika2411  Any updates?

**Comment by krithika2411** [comment]
Working on it . I am  traveling today n tomorrow.  Can i send pr on Saturday

**Comment by MitAbhay** [comment]
@coding-geek21  I would like to complete this, Can you assign this to me ?

**Comment by coding-geek21** [comment]
@krithika2411 Any updates?  It's almost 4 days if you are not making PR by today i will assign  @MitAbhay

**Comment by krithika2411** [comment]
Really sorry @coding-geek21 still traveling u can unassigned me . And sorry for the inconvenience.

**Comment by 11062000** [comment]
I would like to work on this issue kindly see if anything can happen

**Comment by coding-geek21** [comment]
@11062000 any updates?

**Comment by dvlsatya** [comment]
can you assign this to me?

**Comment by dvlsatya** [comment]
@krithika2411 can you please assign this to me?

**Comment by coding-geek21** [comment]
@11062000 any updates?

**Comment by dvlsatya** [comment]
I am having exams, I will complete within 3 days.
