### ISSUE TITLE
Switching to questions on clicking the question no in quiz page

### ISSUE THREAD

**Issue by coding-geek21** [coding-geek21/classDeck#60]
## Is your feature request related to a problem? Please describe.

Currently in our quiz page we can only move to next question after finishing the current question but what if the student want to attend or switch to some other question?

## Describe the solution you'd like...

we should create a grid with all question number, when the student clicks on the question number it should automatically switch to that question

## Screenshots Or Video

this would be the sample video of how this feature should look like 

https://www.awesomescreenshot.com/video/7789747?key=821e495a63c271c074a1cb352a30473c

**Comment by neelam4** [comment]
Hi, I'm interested in resolving this issue. Can I please be assigned this? @coding-geek21

**Comment by coding-geek21** [comment]
@neelam4 any updates?

**Comment by neelam4** [comment]
Currently working on it, I'm having an issue in the setup with "Setting up SECRET_KEY environment variable". Can you please help me out?

**Comment by coding-geek21** [comment]
Can you show me the error you are getting? @neelam4

Did you change the env_template to env file as said in README ?

**Comment by neelam4** [comment]
I'm having problem in logging in as student in local system, it is showing invalid credentials. Because of this, I'm unable to see the UI after changing the HTML code in taken_quiz_form.html .  Please help me with this.

**Comment by coding-geek21** [comment]
Did you signup and confirm your authentication mail? for student account @neelam4

**Comment by neelam4** [comment]
I'm not getting any authentication mail, while running the webapp locally for student account.

**Comment by coding-geek21** [comment]
You should be getting it @neelam4 did you change the env_template to .env file ? And also enter a valid existing mail id

**Comment by coding-geek21** [comment]
Also check the comment in #23 issue you would get idea
