### ISSUE TITLE
Page for creating and managing assignments 

### ISSUE THREAD

**Issue by Ashsenior** [coding-geek21/classDeck#68]
## Define You

- [x] GSSoC22 Participant
- [ ] Contributor

## Is your feature request related to a problem? Please describe.

No page for creating , posting and managing  assignments .

## Describe the solution you'd like...

I will create a page where teachers will create assignments , upload documents and a email notification system for students about the assignments. Teachers will be able to upload assignments , give description and review the submissions , and score them on the basis of their response .

**Comment by Ashsenior** [comment]
Want me to work on it ??

**Comment by coding-geek21** [comment]
@Ashsenior Any updates?

**Comment by Ashsenior** [comment]
Yeah , I have created all the required models and add assignment feature for teachers . Today I'm going to make the student side of the feature .

**Comment by Ashsenior** [comment]
I have created a PR please check . @coding-geek21
