### ISSUE TITLE
Add contributing.md file

### ISSUE THREAD

**Issue by yaswanthsaivendra** [coding-geek21/classDeck#7]
An overview of what u need to add:

- add a desc. of basic disciplinary rules contributors have to follow to maintain a healthy environment
   - things like asking for assignment an issue before starting working on it.
   - creating a pr for assigned issue within a response time of one week , otherwise it will be unassigned etc..
- creating a new branch after setting up the project locally before making any changes, so as to avoid merge conflicts while making prs .
- from now, we will be working on develop branch(master will be used for deployments) , so add a instruction of prs should created for develop branch only.

**Comment by kaustav202** [comment]
I would like to work on it @coding-geek21

**Comment by chinmayparekh** [comment]
I would like to work on it @coding-geek21 @yaswanthsaivendra

**Comment by kaustav202** [comment]
I hope that it can be resolved now. Please let me know if any changes or improvements need to be made.
@coding-geek21 @yaswanthsaivendra
