### ISSUE TITLE
 Add a button that toggles the view of the password on the login and sign-up pages 

### ISSUE THREAD

**Issue by SwathiReddy03** [coding-geek21/classDeck#77]
I am a GSSoC22 Contributor

I would like to add a button that toggles the view of the password (show/hide) on the login and sign-up pages so that the person who entered the password can recheck it.

![image](https://user-images.githubusercontent.com/98385147/162144847-63589bf8-36cc-4569-aea1-9688e6c7208c.png)
![image](https://user-images.githubusercontent.com/98385147/162144863-19821103-4176-4783-b8c8-081ec72ba12c.png)
![image](https://user-images.githubusercontent.com/98385147/162144882-20e2a583-d544-4f1a-81b7-57298d3265fd.png)

I would like to work on it
please assign me this issue

**Comment by coding-geek21** [comment]
@SwathiReddy03 any updates?

**Comment by SwathiReddy03** [comment]
hey 
it was delayed due to exams 
I am working on it 
will finish by tomorrow
