### ISSUE TITLE
Glowing Button Effects

### ISSUE THREAD

**Issue by Geetanjaligupta123** [coding-geek21/classDeck#78]
I want to add glowing effects in all  the Buttons which make this website more attractive

![Screenshot (20)_LI](https://user-images.githubusercontent.com/100347557/162610863-ac34df80-b9a9-42f3-b6c0-7c403e95935c.jpg)
.

**Comment by coding-geek21** [comment]
@geetanjali2001 are you working on this issue? why no updates?

**Comment by Geetanjaligupta123** [comment]
yes, I am working on this issue.

**Comment by coding-geek21** [comment]
Ok make PR soon

> yes, I am working on this issue.

**Comment by coding-geek21** [comment]
Did you complete this issue? how much time will you take for completing this level 1 issue? @geetanjali2001

**Comment by Geetanjaligupta123** [comment]
I'll complete it by 3 days.

**Comment by aaryahjolia** [comment]
Can I work on this ?
