### ISSUE TITLE
account sign up page

### ISSUE THREAD

**Issue by rashita79** [coding-geek21/classDeck#87]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ✔️] I am running the latest version
- [ ✔️] I checked the documentation and found no answer
- [ ✔️] I checked to make sure that this issue has not already been filed

## Define You

- [ ✔️] GSSoC22 Participant
- [✔️ ] Contributor

## Steps to Reproduce

1. 
2. 
3. 
 
## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior
This page could be more user friendly by adding button below for student and teacher below images so it would be more clear and easy UI.

What is the current behavior?

## Screensho
![Screenshot (402)](https://user-images.githubusercontent.com/93339300/165371514-49a14dd8-5538-4169-9fb9-5b3152c1a9a7.png)
ts Or Video

Attach screenshots or video if applicable

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by coding-geek21** [comment]
I don't think that adding a button would be nice. Better you can enhance this page maybe by enhancing the borders of the image adding some box shadows would be better. If you wish to work comment on #71

**Comment by rashita79** [comment]
I wish to work .
