### ISSUE TITLE
Want to add navbar containing Home, about , Login and sign up buttons.

### ISSUE THREAD

**Issue by DeveloperAshish8** [coding-geek21/classDeck#88]
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Define You

- [X] GSSoC22 Participant
- [X] Contributor

## Is your feature request related to a problem? Please describe.

This will provide a better UI Experience and also makes the website responsible and easily navigating

**Comment by coding-geek21** [comment]
Everything is already there so I'm closing this issue. There is no need of adding about button
