### ISSUE TITLE
To improve on hover effects of button

### ISSUE THREAD

**Issue by aaryahjolia** [coding-geek21/classDeck#89]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Define You

- [x] GSSoC22 Participant
- [x] Contributor

## Is your feature request related to a problem? Please describe.

On hovering the button, the color changes to blue, but background is also in same color, so It creates a mess to read the tect.

## Describe the solution you'd like...

Change hovering effects on buttons.

## Screenshots Or Video

![GSSoC](https://user-images.githubusercontent.com/82600388/165990142-cbe0412a-3abc-4c2a-9cb8-3340af7d6c9c.png)

**Comment by coding-geek21** [comment]
I hope #78 is the same as this issue. You comment there if you are interested to work in #78. I'm closing this issue
